resolve #204, #206: support option keys with multi rows
remap-keys/remap pull request #208
Opened 2021-01-20 16:53 UTC by adamrocker

Support multi rows optional keys and set max-width/min-width to keycodes' area.
<img width="1515" alt="スクリーンショット 2021-01-21 1 52 05" src="https://user-images.githubusercontent.com/316463/105207863-664f8000-5b8b-11eb-8afb-46753cc645e1.png">
<img width="1515" alt="スクリーンショット 2021-01-21 1 52 18" src="https://user-images.githubusercontent.com/316463/105207871-68194380-5b8b-11eb-8d50-d592ceb3ef1f.png">

2021-01-20 21:39 UTC, yoichiro requested changes
@adamrocker I posted a few comments. Could you confirm them? Thanks!

2021-01-20 21:39 UTC, yoichiro commented on src/actions/actions.ts
> +      value: { height, width },
```suggestion
      value: { width, height },
```

Of course, your code works, but I think that the pair "width" and "height" should be lined up as "width, height".

2021-01-20 21:39 UTC, yoichiro commented on src/models/KeyboardModel.ts
> +    return this.option == OPTION_DEFAULT || this.choice == '0';
```suggestion
    return this.option == OPTION_DEFAULT || this.isOrigin;
```

I think that the above code will become more understandable code.

2021-01-21 00:18 UTC, merged

2021-01-21 01:52 UTC, monksoffunk commented
Amazingly perfect for Zinc!
Thanks!!