#309 enabled to read every keycode
remap-keys/remap pull request #310
Opened 2021-02-18 21:38 UTC by adamrocker

2021-02-18 22:01 UTC, yoichiro approved these changes
LGTM. Thanks!

2021-02-19 00:49 UTC, adamrocker commented
I made the codes robust.
The original program are assumed all codes are defined in Remap(that means in QMK).
I re-think we should support non predefined keycode because a keyboard designer may assign some QMK-empty keycode to special function.

2021-02-19 01:22 UTC, yoichiro requested changes
2点ほどコメントしました。

2021-02-19 01:22 UTC, yoichiro commented on src/services/hid/Composition.ts
> +const ANY_KEYMAP: IKeymap = anyKeymap(NO_KEYCODE);
`NO_KEYCODE` だとちょっと意図がわからず誤解しちゃったので、名称変更をお願いいたします。

2021-02-19 01:22 UTC, yoichiro commented on src/services/hid/KeycodeList.ts
> +      ret.value = comp.genKeymap() || null;
`comp.genKeymap()` 側を `IKeymap | null` にするほうが良さそうですね。ただ結構なコード変更になりそうなので、今回はこれで大丈夫かと思います。

2021-02-19 01:28 UTC, adamrocker commented on src/services/hid/Composition.ts
> +const ANY_KEYMAP: IKeymap = anyKeymap(NO_KEYCODE);
Sure. I'm gonna clarify the name.

2021-02-19 01:28 UTC, yoichiro approved these changes
LGTM. Thanks!

2021-02-19 01:29 UTC, adamrocker commented on src/services/hid/KeycodeList.ts
> +      ret.value = comp.genKeymap() || null;
I agree with that. We should sweep 'undefined' value out!

2021-02-19 01:39 UTC, merged