Feat 218 save and restore keymap
remap-keys/remap pull request #406
Opened 2021-03-16 09:51 UTC by adamrocker

Enable to save/restore the current device keymap. Keymap data is stored in Firebase ( /keymaps/v1/saves/{id} ).
The data structure is as follow:

```
export type ISavedKeymapData = {
  id?: string; // this entity's id
  author_uid: string; //  auth.uid
  definition_id: string; // /keyboards/v2/definitions/{ID}
  title: string;
  desc: string;
  label_lang: KeyboardLabelLang;
  layout_options: { option: string; optionChoice: string }[] | null;
  keycodes: { [pos: string]: number }[];
  created_at?: Date;
  updated_at?: Date;
};
```

The **title** and **desc** are shown in the Popup to recognize what map it is.

<img width="1362" alt="スクリーンショット 2021-03-16 18 45 53" src="https://user-images.githubusercontent.com/316463/111289472-892c7b00-8688-11eb-8656-c39df5aa2c72.png">
<img width="1363" alt="スクリーンショット 2021-03-16 18 46 15" src="https://user-images.githubusercontent.com/316463/111289483-8cc00200-8688-11eb-8c63-d6669f44d4b5.png">

2021-03-16 13:21 UTC, yoichiro requested changes
@adamrocker Thank you for implementing this great feature!

When I tested this feature, I noticed that there is no validation for filling in the title and the description. If a long description is filled in, the description was not rendered normally. I think that we need to introduce some validation rule. For example, the length of the title should be less than 255, and the length of the description should be less than 512 and applies the word wrap style. How about this?

<img width="392" alt="スクリーンショット 2021-03-16 22 15 51" src="https://user-images.githubusercontent.com/261787/111315716-fb5f8880-86a5-11eb-9ca7-1063d2b1e227.png">

2021-03-17 01:30 UTC, yoichiro requested changes
@adamrocker BTW, if some keyboard definition document in Firestore and it has one or more related keymap documents and the definition is deleted, should the keymap documents be also deleted?

2021-03-17 10:21 UTC, adamrocker commented
@yoichiro 
BTW, if some keyboard definition document in Firestore and it has one or more related keymap documents and the definition is deleted, should the keymap documents be also deleted?
I think, that should be better but ...

2021-03-17 20:32 UTC, adamrocker commented
> I think that we need to introduce some validation rule. For example, the length of the title should be less than 255, and the length of the description should be less than 512 and applies the word wrap style. 

@yoichiro I set the const values to control the text length here.　https://github.com/remap-keys/remap/pull/406/files#diff-9cbafadd4a222bb964cab219655198372c7408c8c78ddcfdd458e9f7ab4c0c54R30-R31

2021-03-17 21:10 UTC, yoichiro commented
> @yoichiro
> 
> > BTW, if some keyboard definition document in Firestore and it has one or more related keymap documents and the definition is deleted, should the keymap documents be also deleted?
> 
> I think, that should be better but ...

Yeah, actually, I guess that there are some cases which we should avoid to delete saved keymaps, and we can delete them later asynchronously. We can decide the way to delete them as a new issue.

2021-03-17 21:13 UTC, yoichiro commented
> > I think that we need to introduce some validation rule. For example, the length of the title should be less than 255, and the length of the description should be less than 512 and applies the word wrap style.
> 
> @yoichiro I set the const values to control the text length here.　https://github.com/remap-keys/remap/pull/406/files#diff-9cbafadd4a222bb964cab219655198372c7408c8c78ddcfdd458e9f7ab4c0c54R30-R31

LGTM!

2021-03-18 02:55 UTC, yoichiro requested changes
@adamrocker I posted some comments, and please confirm them.

2021-03-18 02:55 UTC, yoichiro commented on src/actions/storage.action.ts
> +      console.error(resultList.cause);
@adamrocker In this case, it does not only output a debug log with `console.log`, but it should also show the error notification (and to send a error report via Error Reporting API).

2021-03-18 02:55 UTC, yoichiro commented on src/actions/storage.action.ts
> +      console.error(resultList.cause);
@adamrocker Could you add the logic to show the error notification?

2021-03-21 23:05 UTC, yoichiro commented
@adamrocker Thank you for many changes! I finished reviewing this pull request. I also created some commits to fix some issues. So, I think that this pull request looks good to me, but I want to test this diff a bit. Could you give me a few hours for the testing by me?

2021-03-21 23:41 UTC, yoichiro approved these changes
@adamrocker I tested some use cases, and I could confirmed this worked as I expected. LGTM!

2021-03-22 01:58 UTC, adamrocker commented
@yoichiro We discussed about the type case and got the results as below:
- snake case in DB
- snake case in App with DB's data, however the name of type MUST have 'Data' at the end
- camel case in App

According to above rule, I changed the name of properties this commit https://github.com/remap-keys/remap/pull/406/commits/e8cf84a1e95e209cf97f29579ea1be801310e661

2021-03-22 02:02 UTC, yoichiro commented
@adamrocker LGTM!

2021-03-22 02:03 UTC, merged